server:
  port: 8083

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: TRACE
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    reactor.netty: TRACE

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 647249152856-49n2f7gjar838qg1g0d32dfbofoch8m9.apps.googleusercontent.com
            client-secret: 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
            scope: openid,profile,email
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
  cloud:
    gateway:
      routes:
        - id: circuit-service
          uri: http://${CIRCUIT_SERVICE_BASEURL:localhost:8080}
          predicates:
            - Path=/circuit
            - Method=POST
          filters:
            - SetPath=/api/circuit
        - id: circuit-service-all
          uri: http://${CIRCUIT_SERVICE_BASEURL:localhost:8080}
          predicates:
            - Path=/circuit
            - Method=GET
          filters:
            - SetPath=/api/circuit/all
        - id: race-service
          uri: http://${RACE_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/race
          filters:
            - SetPath=/api/race